apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Địa chỉ DNS nội bộ của các service trong Kubernetes
  # Tên service phải khớp với tên trong các file Service.yaml tương ứng
  CONSUL_HOST: "consul-svc"
  CONSUL_PORT: "8500"
  spring.cloud.consul.host: "consul-svc"
  spring.cloud.consul.port: "8500"
  spring.cloud.consul.discovery.prefer-ip-address: "true"

  KAFKA_BROKERS: "broker-svc:9092"
  
  # JDBC URLs trỏ đến các service database
  SPRING_DATASOURCE_CUSTOMER_DB_URL: "jdbc:postgresql://customerdb-svc:5432/postgres"
  SPRING_DATASOURCE_USERNAME_CUSTOMER_DB: "postgres"
  SPRING_DATASOURCE_PASSWORD_CUSTOMER_DB: "postgres" 
  SPRING_DATASOURCE_CUSTOMER_DB_MAX_LIFETIME: "600000"
  SPRING_DATASOURCE_CUSTOMER_DB_CONNECTION_TIMEOUT: "20000"
  SPRING_DATASOURCE_CUSTOMER_DB_MINIMUM_IDLE: "10"
  SPRING_DATASOURCE_CUSTOMER_DB_MAXIMUM_POOL_SIZE: "50"


  SPRING_DATASOURCE_ORDER_DB_URL: "jdbc:postgresql://orderdb-svc:5432/postgres"
  SPRING_DATASOURCE_USERNAME_ORDER_DB: "postgres"
  SPRING_DATASOURCE_PASSWORD_ORDER_DB: "postgres"
  SPRING_DATASOURCE_ORDER_DB_MAX_LIFETIME: "600000"
  SPRING_DATASOURCE_ORDER_DB_CONNECTION_TIMEOUT: "20000"
  SPRING_DATASOURCE_ORDER_DB_MINIMUM_IDLE: "10"
  SPRING_DATASOURCE_ORDER_DB_MAXIMUM_POOL_SIZE: "50"

  SPRING_DATASOURCE_INVENTORY_DB_URL: "jdbc:postgresql://inventorydb-svc:5432/postgres"
  SPRING_DATASOURCE_USERNAME_INVENTORY_DB: "postgres"
  SPRING_DATASOURCE_PASSWORD_INVENTORY_DB: "postgres"
  SPRING_DATASOURCE_INVENTORY_DB_MAX_LIFETIME: "600000"
  SPRING_DATASOURCE_INVENTORY_DB_CONNECTION_TIMEOUT: "20000"
  SPRING_DATASOURCE_INVENTORY_DB_MINIMUM_IDLE: "10"
  SPRING_DATASOURCE_INVENTORY_DB_MAXIMUM_POOL_SIZE: "50"
