apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  # Đặt tên cho HPA, thường có đuôi -hpa
  name: customer-service-hpa
spec:
  # Chỉ định đối tượng cần được autoscale
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # Tên phải khớp chính xác với tên Deployment của bạn
    name: customer-service-deployment
  
  # Định nghĩa giới hạn co giãn
  minReplicas: 2      # Luôn duy trì ít nhất 2 pod để đảm bảo tính sẵn sàng cao (High Availability)
  maxReplicas: 10     # Cho phép scale lên tối đa 10 pod khi có tải cao
  
  # Định nghĩa các chỉ số để kích hoạt co giãn
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # Mục tiêu: Cố gắng giữ mức sử dụng CPU trung bình của tất cả các pod ở mức 70%
        averageUtilization: 70

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
