apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway
spec:
  # LoadBalancer sẽ tạo ra một địa chỉ IP public (hoặc localhost trên Docker Desktop)
  type: LoadBalancer 
  selector:
    app: api-gateway # Trỏ đến các pod gateway
  ports:
    - protocol: TCP
      port: 8080 # Cổng bạn sẽ truy cập từ bên ngoài (ví dụ: http://localhost:8080)
      targetPort: 8080 # Cổng của container gateway
